Refactor entire codebase
Kerala-Developers/developers_of_kerala_backend pull request #11
Opened 2024-01-13 15:31 UTC by SharonAliyas5573

2024-01-14 12:58 UTC, Sangeeth123sj approved these changes
A really comprehensive update, well done!! @SharonAliyas5573

2024-01-14 17:53 UTC, pranavmadhu01 requested changes

2024-01-14 17:53 UTC, pranavmadhu01 commented on .github/workflows/pre-commit-checks.yml
What does this workflow do?

2024-01-14 17:53 UTC, pranavmadhu01 commented on app/__init__.py
add all init.py to .gitignore

2024-01-14 17:53 UTC, pranavmadhu01 commented on app/api/api_v1/endpoints/user.py
> +                "user_id": str(result.inserted_id),
There is no need to send the user_id along with the response while the user is registered

2024-01-14 17:53 UTC, pranavmadhu01 commented on app/api/api_v1/endpoints/user.py
> +async def register_user(
in register route check for existing user and make sure that the username and mail id is unique for each registered user

2024-01-14 17:53 UTC, pranavmadhu01 commented on app/api/api_v1/endpoints/user.py
> +            "role": user.get("role", ""),
Pass the default value in get function as a developer instead of empty string or remove it and simply use the get function

2024-01-14 18:04 UTC, SharonAliyas5573 commented on .github/workflows/pre-commit-checks.yml
run checks  whenever changes are made to the main branch or when pull requests are opened to the main branch

2024-01-14 18:20 UTC, SharonAliyas5573 commented on app/__init__.py
Typically, `__init__.py` files are included in the repository to define Python packages and ensure the correct functioning of the package structure (package importing).

2024-01-16 06:12 UTC, SharonAliyas5573 commented on app/api/api_v1/endpoints/user.py
> +                "user_id": str(result.inserted_id),
removed

2024-01-16 06:13 UTC, SharonAliyas5573 commented on app/api/api_v1/endpoints/user.py
> +async def register_user(
implemented in latest commit

2024-01-18 16:14 UTC, pranavmadhu01 approved these changes

2024-01-18 16:14 UTC, merged