Implement user profile structure for distinct handling of developer and company details.
Kerala-Developers/developers_of_kerala_backend pull request #3
Opened 2024-01-03 19:17 UTC by SharonAliyas5573

2024-01-03 19:36 UTC, pranavmadhu01 requested changes

2024-01-03 19:36 UTC, pranavmadhu01 commented on models.py
> +class UserRegistration(BaseModel):
should we have seperate classes for user profile and user table we could include the profile pic phone number and full name in user itself

2024-01-03 19:36 UTC, pranavmadhu01 commented on models.py
> +class CompanyProfileUpdate(UserProfileUpdate):
the company will have multiple job posts so instead of keeping skills needed, qualification, job_role, jd  as a direct attribute of the companyProfile table create an attribute called jobs and create a dict of dict which includes all those attributes

2024-01-04 08:47 UTC, Sangeeth123sj commented on models.py
> +class CompanyProfileUpdate(UserProfileUpdate):
That's a good insight and necessary feature, shall we make it as a seperate collection named 'Opening' or something 
so that it can have the relation to the CompanyProfileUpdate with id and all the needed fields like skills needed, qualification, job_role, jd
This will helps keeping the queries and collections more flexible when scaling  @SharonAliyas5573 @pranavmadhu01

2024-01-04 09:00 UTC, pranavmadhu01 commented on models.py
> +class CompanyProfileUpdate(UserProfileUpdate):
yes that will do

2024-01-04 15:33 UTC, SharonAliyas5573 commented on models.py
> +class CompanyProfileUpdate(UserProfileUpdate):
Sure, I'll make the requested updates.

2024-01-05 13:53 UTC, merged